### PR TITLE
Add pseudofun ondemand passenger app

### PR DESCRIPTION
**Pull request by ericfranz**
https://code.osu.edu/wiag/pseudofun

### CODE REVIEW

**Comment by ericfranz** [comment]
@treydock please review

**Comment by treydock** [comment]
@ericfranz If test builds are functional, looks good to me.

**Comment by ericfranz** [comment]
> If test builds are functional, looks good to me.

Actually, running `tito build --rpm --test --builder custom.MockSignBuilder --output $(mktemp -d) --arg mock_config_dir=mock/ --dist=.el7 --arg mock=el7-scl` in the spec's directory fails with error.

**Comment by treydock** [comment]
Build errors will be in `/var/lib/mock/ondemand-scl-7-x86_64/results/build.log`

**Comment by treydock** [comment]
The path in tarball is all screwy.  I blame gitlab.

```
+ cd pseudofun-0.0.1
/var/tmp/rpm-tmp.zLk5Ve: line 35: cd: pseudofun-0.0.1: No such file or directory
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.zLk5Ve (%prep)
    Bad exit status from /var/tmp/rpm-tmp.zLk5Ve (%prep)
```

```
$ tar tvf v0.0.1.tar.gz 
drwxrwxr-x root/root         0 2018-03-09 10:56 pseudofun-v0.0.1-ebaf6f8fa1bba47d43aa286621d945a75f9c4844/
```

**Comment by treydock** [comment]
So either going to have to reference the tag's SHA or not use gitlab.

**Comment by treydock** [comment]
Closing as handled by https://github.com/OSC/ondemand-packaging/commit/096206fab08c337c37dc61e59c1d4020d07e3483

**Pull request closed without merging**
