### PR TITLE
Support building Ubuntu 18.04 packages for OnDemand 2.0

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
@johrstrom It appears like Bundler is 1.x on Ubuntu 18.04. So the only possible way we could support Ubuntu 18.04 is to overwrite the OS bundler with one we provide or one we install with gems which is a really poor sysadmin experience.  I'm inclined to say we can't support Ubuntu 18.04 with OnDemand 2.0.

**Comment by johrstrom** [comment]
> one we install with gems

You're saying because 1.x is on the `PATH` while we're using something in `/opt/ood` -- this is the poor sysadmin experience?

**Comment by treydock** [comment]
The poor sysadmin practice would be touching the OS bundler files.  It might be possible to install the newer bundler gem in /opt/ood, something I'll have to fiddle with.

**Comment by johrstrom** [comment]
That isn't the only discourse topic with Ubuntu 18, I feel like it's fairly popular. the LTS says it'll still get security updates from 2023-2028! lol.

**Comment by johrstrom** [comment]
Oh ok - yea I don't want to maintain or override their bundler. That is I think a stretch, because we'll then be on the hook for updates (until 2028 apparently).

**Comment by treydock** [comment]
Ya I think the tricky part is doing it just for Ubuntu 18.04 and not newer versions.  The Makefile format of deb packages makes that harder than would be with SPEC file format for RPMs.

**Pull request merged**
