### PR TITLE
Support EL8 building and 1.7 prep

### PR DESCRIPTION
**Pull request by treydock**
This contains commit from #66 to keep things simpler. Should merge #66 first.

### CODE REVIEW

**Comment by treydock** [comment]
The runtime RPMs are published to latest repo because that's a weird bootstrap step needed to define build environment that relies on those packages to build up a cache.

**Comment by treydock** [comment]
Moved passenger building spec into this repo. Took the passenger and nginx spec files from upstream and combined them into a single spec that building using our tools. I could not get upstream's build environment to build EL8 packages.

**Comment by ericfranz** [comment]
Does this need merged before I can tag a 1.7.0 release version? That will have the balances feature in the dashboard.

**Comment by treydock** [comment]
First merge #66 then this one may need a rebase as this contains a commit from #66 or can just close out #66 and use this PR.

Once this is merged we'll be building EL7 and EL8.

**Comment by ericfranz** [comment]
@treydock I merged #66 before I saw your latest comment here. Since there are 32 commits here I'm not sure the best way to rebase.

**Comment by treydock** [comment]
I just did a merge to avoid conflicts present with duplicate commits.  Should be good to merge now.

**Pull request merged**
