### PR TITLE
Upgrade passenger to 6.0.20 and NGINX to 1.24.0

### LINKED ISSUE #272: Update Passenger to a newer release
We have a Python 3.9 Passenger app in our OOD deployment, which is causing Passenger to print deprecation warnings like this:

```
App 475 output: /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 475 output:   import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
```

This is apparently fixed in a later Passenger release, here: https://github.com/phusion/passenger/commit/a19753cdb1c5f6048e74db109978382f8982f8e1

Would it be possible to bump the version of Passenger that is packaged for OOD? The newest at the time of writing seems to be `6.0.20` (see their [Releases page](https://github.com/phusion/passenger/releases)).

In addition to this specific python 3.9 fix, Passenger has bumped a lot of their own dependencies as well, so it might be good to keep up with them just in general.

Thanks in advance!

### PR DESCRIPTION
**Pull request by treydock**
Fixes #272

### CODE REVIEW

**Comment by johrstrom** [comment]
I'm restarting the workflows now, but this appears to have broken Debian builds

https://github.com/OSC/ondemand/actions/runs/8879745370?pr=3531

**Comment by treydock** [comment]
https://github.com/OSC/ondemand/pull/3535 - needs to be merged I think.  Looks like apt repos don't support multiple versions of a given package.  I vaguely recall running into this limitation with apt repos.

**Comment by treydock** [comment]
I think to work around that during E2E we'd have to first install the dependencies we want as I think the Control file for deb package won't pull in the one you specify like RPM/yum would do.

**Comment by johrstrom** [comment]
OK thanks, I forgot about that PR or maybe overlooked it.

I'm not too worried about work around and so on. Tests are doing their job - telling us we need to fix something.

**Pull request merged**
